### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by ppedrazzi** [LumaPictures/meteor-jquery-sparklines#1]
I think it's a known issue, but tried installing with no luck.  See terminal:

```
✓ sparklines
    tag: https://github.com/austinrivas/meteor-sparklines.git#v1.0.0

Done installing smart packages

Stand back while Meteorite does its thing

Done installing smart packages

Ok, everything's ready. Here comes Meteor!

=> Errors while scanning packages:

While building package `sparklines`:
error: File not found: /tests/_tests.js

/usr/local/lib/node_modules/meteorite/lib/command.js:35
          throw "Command exited with " + code + "/" + signal;
                                                    ^
Command exited with 1/null
```

**Comment by gjolund** [comment]
Yeah this package is pretty old and is using an older version of meteor / meteorite. I'll update it real quick and make sure it still works with the new Blaze ui.

**Comment by ppedrazzi** [comment]
Awesome.  Thanks!

For now, I am manually putting the js file in client/compatibility and it works fine.

Cheers!

**Comment by gjolund** [comment]
@ppedrazzi I went ahead and updated the package to use blaze components.

Instantiating a sparkline is super simple now.

`{{> sparkline array=someArrayData }}`

Theres tons of other options available at http://sparklines.meteor.com/

Should have the package published tomorrow ( was having an issue with atmosphere ), but if you can wait you can always use the git repo in your `smart.json`.
- Austin

**Comment by ppedrazzi** [comment]
That sounds amazing!  Can’t wait to give it a go!!

**Comment by gjolund** [comment]
@ppedrazzi i just republished the package as `jquery-sparklines` , give it a shot if you're feeling brave :)

**Comment by ppedrazzi** [comment]
I will give it a run - thank you!!!
